name: Main
on:
  # run automatically every hour
  schedule:
    - cron: "0 * * * *"

  # allows to manually run the job at any time
  workflow_dispatch:

  # run on every push on the main branch
  # don't forget to change if you're using 'master' branch
  push:
    branches:
      - main

jobs:
  github-profile-summary-cards:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        with:
          USERNAME: ${{ github.repository_owner }}
          BRANCH_NAME: "main"
          UTC_OFFSET: 9
          EXCLUDE: ""
          AUTO_PUSH: true

# jobs:
#   github-metrics:
#     runs-on: ubuntu-latest
#     steps:
#     - name: Default metrics
#       uses: lowlighter/metrics@latest
#       with:
#         filename: output/metrics.base.svg
#         token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
#         base: header, activity, community, repositories, metadata
#     - name: Most used (with details)
#       uses: lowlighter/metrics@latest
#       with:
#         filename: output/details.svg
#         token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
#         base: ""
#         repositories_skipped: chatbot-ui, gitHub-readme-stats-clone, PL0-compiler, PAMI_Ex13
#         plugin_languages: yes
#         plugin_languages_ignored: >-
#           tex, less, qmake, lex, gnuplot, m4, makefile
#         plugin_languages_details: bytes-size, percentage
#         plugin_languages_limit: 50
#         plugin_languages_threshold: 0%
#         plugin_followup: yes
#         plugin_followup_indepth: yes
#     - name: Compact display
#       uses: lowlighter/metrics@latest
#       with:
#         filename: output/metrics.plugin.achievements.compact.svg
#         token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
#         base: ""
#         plugin_achievements: yes
#         plugin_achievements_only: >-
#          polyglot, stargazer, sponsor, deployer, member, maintainer, developer,
#          scripter, packager, explorer, infographile, manager
#        plugin_achievements_display: compact
#        plugin_achievements_threshold: 0%
